generator:
  pr:
    filters: 256
  h1:
    filters: 128
    strides: [1,1]
    kernel_size: [5,5]
  h2:
    filters: 64
    strides: [2,2]
    kernel_size: [5,5]
  h3:
    filters: 1
    strides: [2,2]
    kernel_size: [5,5]
